ignore:
  - "tests/test_server.cc"
  - "tests/client.cc"
  - "tests/client_stress.cc"
  - "tests/server_config.cc"
  - "tests/client_common.cc"
  - "tests/client_opts.cc"
  - "tests/test_integration.cc"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        informational: true
        paths:
          - "libiqxmlrpc/"

comment:
  layout: "reach, diff, flags, files, tests"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: auto
        informational: true

flags:
  unittests:
    paths:
      - libiqxmlrpc/
    carryforward: true

test_analytics:
  enabled: true
