# OSS-Fuzz project configuration for libiqxmlrpc
# This file should be placed in the OSS-Fuzz projects directory

homepage: "https://github.com/libiqxmlrpc/libiqxmlrpc"
language: c++
primary_contact: "dedkan@gmail.com"
main_repo: "https://github.com/libiqxmlrpc/libiqxmlrpc"
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
