# OSS-Fuzz project configuration for libiqxmlrpc
# This file should be placed in the OSS-Fuzz projects directory

homepage: "https://github.com/yarikmsu/libiqxmlrpc"
language: c++
primary_contact: "ygorbunov@gmail.com"
main_repo: "https://github.com/yarikmsu/libiqxmlrpc"
sanitizers:
  - address
  - undefined
  - memory
  # Coverage mode for guided fuzzing without sanitizer overhead
  - coverage
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
